version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-test-container
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=vocatest-test
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-test-data:/var/lib/mysql
  redis:
    image: redis:6.2
    container_name: redis-test-container
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-test-data:/data

volumes:
  mysql-test-data:
  redis-test-data:
